let id,q,total=7,stream,recognition,started=Date.now(),tick;const u=JSON.parse(localStorage.iqUser||'{"name":"Alex Morgan","role":"Software Developer"}');videoName.textContent=u.name;roleLabel.textContent=u.role||'Software Developer';
function timer(){tick=setInterval(()=>{let s=Math.floor((Date.now()-started)/1000);document.getElementById('timer').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')},500)}
async function camera(){try{stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});cameraEl.srcObject=stream}catch(e){cameraEl.style.display='none';fallback.style.display='grid'}}
const cameraEl=document.getElementById('camera');
function render(x,n){q=x;qtype.textContent=x.type.replace('-',' ').toUpperCase();counter.textContent=`Question ${n} of ${total}`;question.textContent=x.text;answer.value='';words.textContent='0 words';progress.textContent=`${n-1} of ${total} questions answered`;document.querySelectorAll('.mapitem').forEach((e,i)=>{e.classList.toggle('active',i===n-1);e.classList.toggle('done',i<n-1)});let p=Math.round((n-1)/total*100);circle.textContent=p+'%';circle.style.background=`conic-gradient(#2f72e8 ${p*3.6}deg,#edf1f6 ${p*3.6}deg)`;coach.textContent=x.type==='technical'?'Explain the concept, then give a practical example.':x.type==='behavioral'?'Use a specific situation and explain what you personally did.':'Talk through your reasoning step by step.'}
async function start(){try{let r=await fetch('/api/interviews/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role:u.role||'Software Developer',count:7,difficulty:'Mixed'})}).then(x=>x.json());id=r.interviewId;total=r.total;render(r.question,1);let all=await fetch('/api/interviews/'+id).then(x=>x.json());map.innerHTML=all.questions.map((x,i)=>`<div class="mapitem ${i?'':'active'}"><b>${i+1}</b>${x.type.replace('-',' ')} · ${x.difficulty}</div>`).join('');bars.innerHTML=Array(total).fill(0).map(()=>'<i></i>').join('')}catch(e){alert(e.message);location='/dashboard.html'}}
async function submitAnswer(){let a=answer.value.trim();if(!a){answer.focus();return}submit.disabled=true;submit.textContent='Analyzing...';try{let r=await fetch('/api/interviews/'+id+'/answer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({questionId:q.id,answer:a})}).then(x=>x.json());coach.textContent=r.analysis.feedback+' Score: '+r.analysis.score+'/100.';if(r.nextQuestion&&r.questionNumber<=total)render(r.nextQuestion,r.questionNumber);else await complete()}catch(e){alert(e.message)}submit.disabled=false;submit.textContent='Submit answer →'}
async function complete(){clearInterval(tick);if(stream)stream.getTracks().forEach(t=>t.stop());let r=await fetch('/api/interviews/'+id+'/complete',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).then(x=>x.json());score.textContent=r.score;ft.textContent=r.metrics.technical+'%';fc.textContent=r.metrics.communication+'%';fp.textContent=r.metrics.problemSolving+'%';ff.textContent=r.metrics.confidence+'%';summary.textContent=r.score>=80?'Strong structure and useful detail.':r.score>=65?'Solid foundation; add more specific examples.':'Keep practicing structure, detail and reasoning.';modal.classList.add('show')}
answer.oninput=()=>words.textContent=answer.value.trim().split(/\s+/).filter(Boolean).length+' words';submit.onclick=submitAnswer;finish.onclick=()=>confirm('Finish this interview now?')&&complete();end.onclick=()=>confirm('End this interview?')&&complete();close.onclick=()=>location='/dashboard.html';
mic.onclick=()=>{if(stream){let t=stream.getAudioTracks()[0];if(t)t.enabled=!t.enabled;mic.textContent=t&&t.enabled?'🎙':'🔇'}};cam.onclick=()=>{if(stream){let t=stream.getVideoTracks()[0];if(t)t.enabled=!t.enabled;cam.textContent=t&&t.enabled?'▣':'□'}};
voice.onclick=()=>{let R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return alert('Speech recognition is not supported in this browser.');recognition=new R();recognition.continuous=true;recognition.interimResults=true;recognition.lang='en-US';voice.textContent='● Listening...';recognition.onresult=e=>{let s='';for(let i=e.resultIndex;i<e.results.length;i++)s+=e.results[i][0].transcript;answer.value=s;answer.oninput()};recognition.onend=()=>voice.textContent='🎙 Use voice';recognition.start()};
timer();camera();start();